services:
  postgres:
    image: postgres:latest
    container_name: test
    restart: unless-stopped
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: FbDz5H5x4RYnyctpdXfmk18g7geTv3Aecm85bmyHDZUbmIb2AMXy7mbHIJx0r5sQ
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
